### ISSUE TITLE
Clustering/lib/Kmeanspp.m中的一些问题

### ISSUE THREAD

**Issue by ruoxu-wang** [AaronX121/Clustering#1]
您好！我正在学习K-mean++聚类的方法，您的程序给了我巨大的帮助，非常感谢！但是我对您Clustering/lib/Kmeanspp.m中的一部分不太理解，具体而言是该程序的20、21行重复调用了变量k，这是否会影响程序的运行，期望您能提供帮助！

**Comment by duanguanhua** [comment]
把第20、21行变量k换一个变量名（如换为m）

**Comment by ruoxu-wang** [comment]
感谢您的帮助！谢谢！
