### ISSUE TITLE
Error Clustering (line 41)     PlotData(data, result, centroid);

### ISSUE THREAD

**Issue by chocolate-771** [AaronX121/Clustering#4]
Hello ,how to solve more than three-dimensional or even more dimensional data？

**Comment by xuyxu** [comment]
Hi, thanks for reporting. To clarify, what is the shape of your input data?

It looks like this is a error on the side of `PlotData`. The clustering algorithm should work fine on data with more than 3 dimensions.

**Comment by chocolate-771** [comment]
The input data is a 480x182 matrix, and each row is taken as a sample.

**Comment by chocolate-771** [comment]
输入数据为480x182的矩阵，把每一行作为一个样本。

画图的函数里定义了：
if((p > 3) || (p < 1))
    error('Unable to plot data exceeds 3-deminsion');
end

是因为这个原因吗？

**Comment by chocolate-771** [comment]
Defined in the drawing function:
if((p> 3) || (p <1))
     error('Unable to plot data exceeds 3-deminsion');
end

Is it for this reason?

**Comment by xuyxu** [comment]
Yes, the scatter / scatter3 function in MATLAB cannot handle data with more than 3 dimensions.

Here are two suggestions for your problem:
* Try to pass a subspace of data into `PlotData`, for example, you can manually select 2 or 3 dimensions;
* Use t-SNE on Python, which is a great tool on visualizing high dimensional data. You may find this link helpful: https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html. In addition, you should use `scipy.io.loadmat` to load your .mat data.

**Comment by chocolate-771** [comment]
Thank for your reply

**Comment by xuyxu** [comment]
Feel free to open another one if you have any problem ;-).
